[phases.setup]
nixPkgs = ["nodejs-18_x", "npm", "python3", "gcc"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["NODE_ENV=production npm run start"] 