[phases.setup]
nixPkgs = ["...", "python3", "gcc"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["npm install --omit=dev --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production npm run start" 